{% set version = '1.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-metap
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/metap_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/metap/metap_{{ version }}.tar.gz
  sha256: 7fcf148bfd77f445b2ee68cbd2367caaf991028d9843020c755dd11965adb5ca

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rdpack
    - r-tfisher
    - r-lattice
    - r-mutoss
  run:
    - r-base
    - r-rdpack
    - r-tfisher
    - r-lattice
    - r-mutoss

test:
  commands:
    - $R -e "library('metap')"           # [not win]
    - "\"%R%\" -e \"library('metap')\""  # [win]

about:
  home: http://www.dewey.myzen.co.uk/meta/meta.html
  license: GPL-2-only
  summary: The canonical way to perform meta-analysis involves using effect sizes. When they
    are not available this package provides a number of methods for meta-analysis of
    significance values including the methods of Edgington, Fisher, Lancaster, Stouffer,
    Tippett, and Wilkinson; a number of data-sets to replicate published results; and
    a routine for graphical display.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: metap
# Type: Package
# Title: Meta-Analysis of Significance Values
# Version: 1.3
# Date: 2020-01-22
# Authors@R: person("Michael", "Dewey", role = c("aut", "cre"), email = "lists@dewey.myzen.co.uk", comment = c(ORCID = "0000-0002-7522-3677") )
# Description: The canonical way to perform meta-analysis involves using effect sizes. When they are not available this package provides a number of methods for meta-analysis of significance values including the methods of Edgington, Fisher, Lancaster, Stouffer, Tippett, and Wilkinson; a number of data-sets to replicate published results; and a routine for graphical display.
# URL: http://www.dewey.myzen.co.uk/meta/meta.html
# Imports: lattice,Rdpack,TFisher,mutoss
# RdMacros: Rdpack
# License: GPL-2
# LazyLoad: yes
# NeedsCompilation: no
# Packaged: 2020-01-22 07:23:23 UTC; MichaelUser
# Author: Michael Dewey [aut, cre] (<https://orcid.org/0000-0002-7522-3677>)
# Maintainer: Michael Dewey <lists@dewey.myzen.co.uk>
# Repository: CRAN
# Date/Publication: 2020-01-23 19:10:05 UTC
