appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 1baf9OQ85Y90FRPqhA3ET/iAKaQWLuWUEGLblNIsVGL/RxqNsDEh2LvxeT+qa7iLwAGOF2IL7hbCbMQ0ZLOXNOGeyGANYZTIwpJSPfqOVFH684sr++RYx8ugdOZQ6QJX7TSpYqgHM0XJN1FCj/YvaTbzFnWGOgVKY/y5duSeMKdmDHLCnKm/5w1O9D/AdH4AAKjTRAP3od3N447AoZrP9BAxOvBT52/Qvw8+MW/ls2U9QBrwKt3953rwgZR9KSr649uxFkTiqLuj54NlvydZkGVECQ9NWlwE7uv3WA3x2M0lNiM7nAon3/JVqRvKxb0n+OQ0PiKjRCTmmmX2wVHhaAGYLUg7N3BgQW8WMy+mYRjwCyj6IvpL77cXdBQT2qR9U++CgpHK4xyaKIbuLshJFzSA5ulzjwwTmNFVM8H9eWOA+bkCff+KJT1p9Jw2zmtu8GeHajXYfCyL48FiQy3QM7O4K1LcuZT24DdzApsw5HSLUORNa1LKvzGWkgLzu/AoehVjDz1Ipkaj9yr3XkfSECZTs6XQj1qt8LPtBfkypDWJXHtb6uqTzVMCqZCElWfTC/ByazLfXMPPVJrUY0zdnUSu+BAlMflfi/3wUKQlomAvzUplgo5llsFkwi7t0P6HAGUVkA76cUUCpCeTLT2+6NwmHbU1M2sGqO5ULmNsU9c=}
