travis:
  secure:
    BINSTAR_TOKEN: xKIOiearC9i8JKxy6ZdjLFD/m+npuxOZL1dGaUd5i6kI14UHnp/PIUKOHdI9eQaTppgwpHq8QfrSM/W8gdV1VbYg9L1D+I2yOst4PWTWsDSt9RLzaqtf88kDUL6jzVivsPN/gOOKhWHUGw0nbO1OGcv2G/Z3+u/dSUPVygoNHCLQEY/8NrVsgePct4+9Y7/qUQEI3Wnf6rOxhWskkmsFEnaC7APkZCJrHalZPclTAk9bOiYJizBhE69UQ7sc6z4i771HC2oSse7PDR533C9iH2tmXXRwzQJROMwvxe9Z/Yguz/vVQDBopTjf8rZq5PynOMywGt6xQmmrut5aSGJc4wT0zan+EyngPyv/zO7mQ35U7I4VCs0I2Z+9AW33Chb6mDzBMf5ckv/VMt0hEj5Gfym9jXUdsNklih1S7IQ/SOJEmsxsdQrvQTbHM75o/R7xakBHUNkq90HTdTd2aEf36sLPPKcJThykDqxSZ9VIBjFTwre1Xsi/qhmE1Mu9MMyyYC/4bVY6rMZTyqHji2fMJIVKfl24GxYhqcvKUpjXXKUNaabrJmKjq2L/3NqxQ/NbwcMmlaAIR7Ub0EKXAPgjaiqueSIDXjPmvkuVXBykX5hnXMar+jwy8pNt5lSm1cA905lBXpB8Bg6s9YOM5SU/mhxsU/Lo6EEJpH5a201TTfc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
